feat: add node metrics doc
dominant-strategies/quai-docs pull request #108
Opened 2024-05-07 16:40 UTC by Juuddi

- Add node metrics config doc as per: https://github.com/dominant-strategies/go-quai/pull/1704/files
- Rework a few of the sidebar_labels for node, miner, stratum

2024-05-07 16:43 UTC, gameofpointers requested changes
why are we commiting a random package-lock.json ? @Juuddi

2024-05-07 16:44 UTC, Juuddi commented
> why are we commiting a random package-lock.json ? @Juuddi

Cleaned out the old deps and reinstalled, should just be the latest package-lock

2024-05-07 16:45 UTC, Djadih requested changes

2024-05-07 16:45 UTC, Djadih commented on static/img/GrafanaDashboard.png
Is there space to include the other screenshots? We should actually have explainers on what each metric means to the average user

2024-05-07 16:46 UTC, Juuddi commented on static/img/GrafanaDashboard.png
Yeah there's plenty of room, just drop me some explainers on all of the metrics you want to highlight and I can throw them in

2024-05-07 16:54 UTC, Djadih commented on static/img/GrafanaDashboard.png
Should be similar to this
https://geth.ethereum.org/docs/monitoring/understanding-dashboards

2024-05-07 16:57 UTC, Djadih commented on static/img/GrafanaDashboard.png
Happy to help if any are unclear just come by my desk, but basically these should be from a user perspective like in the example above

2024-05-07 17:00 UTC, Juuddi commented on static/img/GrafanaDashboard.png
Definitely a nice-to-have but for the most part I would assume this content would go in a go-quai specific docs page, similar to how this is in the geth docs, not the ethereum docs.

If you want all of this content in the docs here, I'll need a general overview of what changes between geth and go-quai metrics, to what extent of the content you want to include, and all of the screenshots as well. Might be best for you to write this as you have the subject matter knowledge.

2024-05-07 17:39 UTC, Djadih commented on static/img/GrafanaDashboard.png
I see what you mean now, I agree with the distinction between protocol and client docs so if we set that up and have a docs page for go-quai I'm all for it, and that can be done at a future date.

For the second part I don't think that all client related docs require full time effort from protocol development as the user facing changes in this (and many) cases are minimal and imo shouldn't be beyond the expertise of people we have writing the docs (they have experience with the product and direct access to the devs to ask). Considering that product development is still in full swing I just don't think we have the bandwidth or resources to devote protocol resources in every case.

2024-05-17 15:07 UTC, wizeguyy commented on docs/participate/node/node-monitoring.md
> +Monitoring your node's performance in real time is crucial to ensure that it is running smoothly and efficiently. The go-quai client bundles a monitoring solution that allows you to track the health
I might dial this back a bit. 99% of people never need to run metrics or graphana or anything, so I wouldn't call this a crucial activity. Its more of a tool for advanced users who would like to understand the node's performance on their system.

2024-05-17 15:09 UTC, wizeguyy commented on docs/participate/stratum-proxy/stratum-faq.md
> +| Hydra      | Region |             | 8583            |                                                            |
:muscle:

2024-05-17 15:38 UTC, Juuddi commented on docs/participate/node/node-monitoring.md
> +Monitoring your node's performance in real time is crucial to ensure that it is running smoothly and efficiently. The go-quai client bundles a monitoring solution that allows you to track the health
Agree with you here. Language has been fixed in [29af5bc](https://github.com/dominant-strategies/quai-docs/pull/108/commits/29af5bcdadde6a376392f31ab2806ec9b5ce82ac)

2024-05-17 15:39 UTC, Djadih approved these changes

2024-05-28 16:40 UTC, merged